import React, { useState, useEffect, useRef } from 'react'
import RupeeInput from '../components/RupeeInput'
import ModalOverlay from '../components/ModalOverlay'
import { X } from 'lucide-react'
import { showToast } from '../components/Toast'
import SearchableSelect from '../components/SearchableSelect'
import { useT } from '../i18n'
interface Props {
  onClose: () => void
  onCreated: () => void
  incomeTypes: Array<{ id: number; name: string; standard_amount: number; is_active: number; category_group: string; code?: string | null }>
  wallets: Array<{ id: number; name: string; is_active: number }>
  assets: Array<{ id: number; name: string }>
  // Pre-selects the payer (counter flow: scan card → member profile → Record Payment)
  initialMemberId?: number
}

// ── Adaptive form configuration per income type (Requirement 3, v2.0) ──
// Loan Interest / Loan Fine are system-generated by the Loan module and
// are never available for manual entry.
const HIDDEN_CODES = ['loan_interest', 'loan_fine']

const MEMBER_CODES = ['membership_fee', 'entrance_fee', 'fine']
const ONE_TIME_CODES = ['membership_fee', 'entrance_fee']

const BUILDING_SOURCES = [
  'Building Rental',
  'Electricity Bill Reimbursement',
  'Water Bill Reimbursement',
  'Damage Compensation',
  'Other Building-related Charges'
]
const ASSET_SOURCES = ['Asset Rental', 'Asset Sale']

export default function AddIncomeModal({ onClose, onCreated, incomeTypes, wallets, assets, initialMemberId }: Props): React.ReactElement {
  const { t } = useT()

  const activeWallets = wallets.filter(w => w.is_active == 1)
  const activeIncomeTypes = incomeTypes.filter(it => it.is_active == 1 && !HIDDEN_CODES.includes(it.code || ''))

  const [members, setMembers] = useState<Array<{ id: number; nic: string; full_name: string }>>([])
  const [submitting, setSubmitting] = useState(false)

  // Form State — income type is selected first; the rest of the form adapts
  const [incomeTypeId, setIncomeTypeId] = useState<number | ''>('')
  const [date, setDate] = useState(new Date().toISOString().split('T')[0])
  const [memberId, setMemberId] = useState<number | ''>(initialMemberId ?? '')
  const [payerType, setPayerType] = useState<'Member' | 'Guest'>('Member')
  const [guestName, setGuestName] = useState('')
  const [amountStr, setAmountStr] = useState('')
  const [paymentMethod, setPaymentMethod] = useState<'Cash' | 'Bank Transfer' | 'Cheque'>('Cash')
  const [walletId, setWalletId] = useState<number | ''>('')
  const [assetId, setAssetId] = useState<number | ''>('')
  const [fineReason, setFineReason] = useState('')
  const [incomeSource, setIncomeSource] = useState('')
  const [notes, setNotes] = useState('')

  useEffect(() => {
    window.api.members.getAllSlim().then(setMembers)
  }, [])

  const selectedType = activeIncomeTypes.find(it => it.id === Number(incomeTypeId))
  const code = selectedType?.code || ''

  const isMemberType = MEMBER_CODES.includes(code)
  const isFine = code === 'fine'
  const isFuneralFood = code === 'funeral_food_collection'
  const isBankInterest = code === 'bank_interest'
  const isBuilding = code === 'building_income'
  const isAsset = code === 'asset_income'
  const isOther = code === 'other_income'
  const isGeneric = code === '' && selectedType !== undefined // custom type without a code

  // Reset adaptive fields whenever the income type changes
  useEffect(() => {
    if (incomeTypeId === '') return
    if (selectedType && selectedType.standard_amount > 0) {
      setAmountStr((selectedType.standard_amount / 100).toFixed(2))
    } else {
      setAmountStr('')
    }
    setMemberId(initialMemberId ?? '')
    setGuestName('')
    setAssetId('')
    setFineReason('')
    setIncomeSource(isBuilding ? BUILDING_SOURCES[0] : isAsset ? ASSET_SOURCES[0] : '')
    setPayerType(isMemberType || isGeneric ? 'Member' : 'Guest')
  }, [incomeTypeId])

  const handleSubmit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault()

    if (incomeTypeId === '') {
      showToast('error', t('iform.selectTypeFirst'))
      return
    }

    const memberRequired = isMemberType || ((isOther || isGeneric) && payerType === 'Member')
    if (memberRequired && memberId === '') {
      showToast('error', t('common.pleaseMember'))
      return
    }
    if ((isOther || isGeneric) && payerType === 'Guest' && !guestName.trim()) {
      showToast('error', t('iform.enterPayerName'))
      return
    }
    if (isFine && !fineReason.trim()) {
      showToast('error', t('iform.enterFineReason'))
      return
    }
    if (isAsset && assetId === '') {
      showToast('error', t('iform.selectAssetIncome'))
      return
    }
    if (isOther && !notes.trim()) {
      showToast('error', t('iform.enterDescIncome'))
      return
    }
    if (walletId === '') {
      showToast('error', t('common.pleaseWallet'))
      return
    }

    const amountCents = Math.round(Number(amountStr) * 100)
    if (amountCents <= 0) {
      showToast('error', t('wform.amountGtZero'))
      return
    }

    // Non-member income sources are recorded against a descriptive payer name
    let effectivePayerType: 'Member' | 'Guest' = memberRequired ? 'Member' : 'Guest'
    let effectiveGuestName: string | null = null
    if (effectivePayerType === 'Guest') {
      effectiveGuestName = guestName.trim() ||
        (incomeSource ? incomeSource : selectedType?.name || 'External')
    }

    setSubmitting(true)
    try {
      await window.api.income.create({
        date,
        payer_type: effectivePayerType,
        member_id: effectivePayerType === 'Member' ? memberId : null,
        guest_name: effectiveGuestName,
        income_type_id: incomeTypeId,
        amount: amountCents,
        fine_reason: isFine ? fineReason.trim() : null,
        payment_method: paymentMethod,
        wallet_id: walletId,
        asset_id: isAsset && assetId !== '' ? assetId : null,
        notes: incomeSource && !isAsset ? `${incomeSource}${notes.trim() ? ` — ${notes.trim()}` : ''}` : notes.trim()
      })
      showToast('success', t('iform.recorded'))
      onCreated()
      onClose()
    } catch (error: any) {
      showToast('error', error.message || t('iform.recordFailed'))
      setSubmitting(false)
    }
  }

  return (
    <ModalOverlay onClose={onClose} guardUnsaved>
      <div className="modal" role="dialog" aria-label={t('iform.title')} aria-modal="true">
        <div className="modal-header gradient-header">
          <h3>{t('iform.title')}</h3>
          <button className="btn-icon" onClick={onClose} aria-label={t('common.close')}><X size={20} /></button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="modal-body">
            {/* Step 1 — income type drives the rest of the form */}
            <div className="form-group full-width">
              <label>{t('iform.incomeType')} <span style={{ color: 'var(--danger)' }}>*</span></label>
              <select className="form-control" value={incomeTypeId} onChange={(e) => setIncomeTypeId(Number(e.target.value))} required autoFocus>
                <option value="" disabled>{t('iform.selectIncomeType')}</option>
                {activeIncomeTypes.map(it => (
                  <option key={it.id} value={it.id}>{it.name}</option>
                ))}
              </select>
              {ONE_TIME_CODES.includes(code) && (
                <small style={{ color: 'var(--text-secondary)' }}>
                  {t('iform.oneTimeNote', { name: selectedType?.name || '' })}
                </small>
              )}
              {isFuneralFood && (
                <small style={{ color: 'var(--text-secondary)' }}>
                  {t('iform.funeralFoodNote')}
                </small>
              )}
            </div>

            {incomeTypeId !== '' && (
              <>
                {/* Payer — adapts to the selected type */}
                {(isOther || isGeneric) && (
                  <div className="form-group full-width">
                    <label>{t('iform.payerType')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                    <select className="form-control" value={payerType} onChange={(e) => setPayerType(e.target.value as any)}>
                      <option value="Member">{t('iform.registeredMember')}</option>
                      <option value="Guest">{t('iform.guestExternal')}</option>
                    </select>
                  </div>
                )}

                {(isMemberType || ((isOther || isGeneric) && payerType === 'Member')) && (
                  <div className="form-group full-width">
                    <label>{t('common.member')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                    <SearchableSelect
                      options={members.map(m => ({ value: m.id, label: m.full_name, sublabel: m.nic }))}
                      value={memberId}
                      onChange={(val) => setMemberId(Number(val))}
                      placeholder={t('lform.selectMember')}
                      required
                    />
                  </div>
                )}

                {(isOther || isGeneric) && payerType === 'Guest' && (
                  <div className="form-group full-width">
                    <label>{t('iform.payerName')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                    <input type="text" className="form-control" value={guestName} onChange={(e) => setGuestName(e.target.value)} required placeholder={t('iform.payerNamePlaceholder')} />
                  </div>
                )}

                {(isFuneralFood || isBankInterest || isBuilding) && (
                  <div className="form-group full-width">
                    <label>{t('iform.receivedFrom')} <span style={{ color: 'var(--text-secondary)', fontWeight: 400 }}>{t('iform.optional')}</span></label>
                    <input
                      type="text"
                      className="form-control"
                      value={guestName}
                      onChange={(e) => setGuestName(e.target.value)}
                      placeholder={isBankInterest ? t('iform.phBankInterest') : isBuilding ? t('iform.phBuilding') : t('iform.phFuneralFood')}
                    />
                  </div>
                )}

                {/* Type-specific fields */}
                {isFine && (
                  <div className="form-group full-width">
                    <label>{t('iform.reasonForFine')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                    <input type="text" className="form-control" value={fineReason} onChange={(e) => setFineReason(e.target.value)} required placeholder={t('iform.fineReasonPlaceholder')} />
                  </div>
                )}

                {isBuilding && (
                  <div className="form-group full-width">
                    <label>{t('iform.buildingSource')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                    <select className="form-control" value={incomeSource} onChange={(e) => setIncomeSource(e.target.value)} required>
                      {BUILDING_SOURCES.map(s => <option key={s} value={s}>{s}</option>)}
                    </select>
                  </div>
                )}

                {isAsset && (
                  <div className="form-grid">
                    <div className="form-group">
                      <label>{t('iform.assetSource')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                      <select className="form-control" value={incomeSource} onChange={(e) => setIncomeSource(e.target.value)} required>
                        {ASSET_SOURCES.map(s => <option key={s} value={s}>{s}</option>)}
                      </select>
                    </div>
                    <div className="form-group">
                      <label>{t('iform.asset')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                      <select className="form-control" value={assetId} onChange={(e) => setAssetId(Number(e.target.value))} required>
                        <option value="" disabled>{t('iform.selectAssetOpt')}</option>
                        {assets.map(a => (
                          <option key={a.id} value={a.id}>{a.name}</option>
                        ))}
                      </select>
                    </div>
                  </div>
                )}

                {/* Common fields */}
                <div className="form-grid">
                  <div className="form-group">
                    <label>{t('wform.amountRs')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                    <RupeeInput style={{ fontWeight: 700, color: 'var(--success)' }} value={amountStr} onChange={setAmountStr} required />
                  </div>
                  <div className="form-group">
                    <label>{t('common.date')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                    <input type="date" max={new Date().toISOString().split('T')[0]} className="form-control" value={date} onChange={(e) => setDate(e.target.value)} required />
                  </div>
                </div>

                <div className="form-grid">
                  <div className="form-group">
                    <label>{t('lform.paymentMethod')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                    <select className="form-control" value={paymentMethod} onChange={(e) => setPaymentMethod(e.target.value as any)} required>
                      <option value="Cash">{t('lform.pmCash')}</option>
                      <option value="Bank Transfer">{t('lform.pmBankTransfer')}</option>
                      <option value="Cheque">{t('lform.pmCheque')}</option>
                    </select>
                  </div>
                  <div className="form-group">
                    <label>{t('lform.depositToWallet')} <span style={{ color: 'var(--danger)' }}>*</span></label>
                    <select className="form-control" value={walletId} onChange={(e) => setWalletId(Number(e.target.value))} required>
                      <option value="" disabled>{t('wform.selectWallet')}</option>
                      {activeWallets.map(w => (
                        <option key={w.id} value={w.id}>{w.name}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="form-group full-width">
                  <label>
                    {isOther ? <>{t('iform.description')} <span style={{ color: 'var(--danger)' }}>*</span></> : t('lform.notesRef')}
                  </label>
                  <input type="text" className="form-control" value={notes} onChange={(e) => setNotes(e.target.value)} required={isOther} placeholder={isOther ? t('iform.descPlaceholder') : t('iform.notesPlaceholder')} />
                </div>
              </>
            )}
          </div>

          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={onClose} disabled={submitting}>{t('common.cancel')}</button>
            <button type="submit" className="btn btn-primary" disabled={submitting || incomeTypeId === ''}>
              {submitting ? t('lform.recording') : t('iform.title')}
            </button>
          </div>
        </form>
      </div>
    </ModalOverlay>
  )
}
