#!/usr/bin/env bash
# One-time cutover of PROD from pm2 + host MySQL to the Docker platform stack.
# Run ON the prod server from /opt/esamithi-stack, inside the agreed
# maintenance window (~15 min):
#
#   SLUG=<samithi-slug> NAME="<Display Name>" INTERNAL_SECRET=<from-platform> bash cutover.sh
#
# What it does, in order:
#   1. sanity checks + builds the API image while pm2 still serves traffic
#   2. generates the stack .env (preserves the legacy JWT_SECRET so every
#      existing staff/member token keeps working; new MySQL root + tenant pw)
#   3. stops pm2 + host nginx        ← downtime starts
#   4. final dump of the live DB from host MySQL → import into container
#      MySQL under a dedicated per-tenant user
#   5. starts the full stack, waits healthy, smoke-checks   ← downtime ends
#
# ROLLBACK at any point:
#   sudo docker compose down && sudo systemctl start nginx && pm2 restart esamithi-api
#   (/opt/esamithi and host MySQL are never modified by this script)
set -euo pipefail
cd "$(dirname "$0")"
LEGACY=/opt/esamithi

[ -n "${SLUG:-}" ] || { echo "SLUG=<samithi-slug> required (e.g. SLUG=wadduwa01)"; exit 1; }
[ -n "${NAME:-}" ] || { echo "NAME=\"<Display Name>\" required"; exit 1; }
[[ "$SLUG" =~ ^[a-z0-9][a-z0-9_-]{1,19}$ ]] || { echo "Bad slug"; exit 1; }
[ -n "${INTERNAL_SECRET:-}" ] || { echo "INTERNAL_SECRET=<value from platform .env> required"; exit 1; }
[ -f /opt/esamithi-server/Dockerfile ] || { echo "/opt/esamithi-server missing — run stage-prod.sh from the workstation first"; exit 1; }
sudo docker compose version >/dev/null 2>&1 || { echo "docker compose plugin missing"; exit 1; }

get() { sudo grep "^$1=" "$LEGACY/.env" | head -1 | cut -d= -f2-; }
LEGACY_JWT=$(get JWT_SECRET); LEGACY_DB=$(get DB_NAME)
[ -n "$LEGACY_JWT" ] || { echo "Could not read legacy JWT_SECRET"; exit 1; }
DB_NAME=${LEGACY_DB:-esamithi}
DB_USER="${SLUG//-/_}_app"

echo "── 1/5 Building API image (pm2 still serving)"
sudo docker compose build api
sudo docker compose pull nginx mysql 2>/dev/null || true

echo "── 2/5 Stack .env + tenants.json"
if [ -f .env ]; then
  echo ".env exists — reusing existing passwords (re-run)"
else
  MYSQL_ROOT_PASSWORD=$(openssl rand -hex 16)
  TENANT_DB_PASSWORD=$(openssl rand -hex 12)
  cat > .env <<ENV
# eSamithi prod stack — generated by cutover.sh $(date -u +%Y-%m-%dT%H:%MZ)
NODE_ENV=production
PORT=3000
DB_HOST=mysql
JWT_SECRET=$LEGACY_JWT
JWT_EXPIRES_IN=24h
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
TENANT_DB_PASSWORD=$TENANT_DB_PASSWORD
DEFAULT_TENANT=$SLUG
INTERNAL_SECRET=$INTERNAL_SECRET
ENV
  chmod 600 .env
fi
ROOT_PW=$(grep '^MYSQL_ROOT_PASSWORD=' .env | cut -d= -f2-)
TEN_PW=$(grep '^TENANT_DB_PASSWORD=' .env | cut -d= -f2-)

# Inline db_password: byte-compatible with what the platform's registry sync
# will push once this server is registered on the console.
cat > tenants.json <<JSON
{
  "$SLUG": {
    "name": $(node -e "console.log(JSON.stringify(process.argv[1]))" "$NAME"),
    "db": "$DB_NAME",
    "status": "active",
    "db_user": "$DB_USER",
    "db_password": "$TEN_PW"
  }
}
JSON

echo "── 3/5 Stopping pm2 + host nginx (DOWNTIME STARTS)"
pm2 stop esamithi-api || true
sudo systemctl stop nginx
sudo systemctl disable nginx >/dev/null 2>&1 || true

echo "── 4/5 Final dump → container MySQL"
DUMP=/tmp/esamithi-cutover-$(date +%s).sql
sudo mysqldump --single-transaction --no-tablespaces --set-gtid-purged=OFF --routines --triggers "$DB_NAME" > "$DUMP"
echo "  dump: $(wc -c < "$DUMP") bytes"

sudo docker compose up -d mysql
echo "  waiting for container MySQL…"
for i in $(seq 1 60); do
  if sudo docker compose exec -T mysql mysql -h127.0.0.1 -uroot -p"$ROOT_PW" -e 'SELECT 1' >/dev/null 2>&1; then break; fi
  sleep 3
  [ "$i" = 60 ] && { echo "container MySQL never became ready"; exit 1; }
done

sudo docker compose exec -T mysql mysql -uroot -p"$ROOT_PW" <<SQL
CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$TEN_PW';
ALTER USER '$DB_USER'@'%' IDENTIFIED BY '$TEN_PW';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'%';
FLUSH PRIVILEGES;
SQL
sudo docker compose exec -T mysql mysql -uroot -p"$ROOT_PW" "$DB_NAME" < "$DUMP"
echo "  imported"

echo "── 5/5 Starting the stack"
sudo docker compose up -d
echo "  waiting for API health…"
for i in $(seq 1 40); do
  if curl -sf http://127.0.0.1/api/v1/health >/dev/null 2>&1; then break; fi
  sleep 3
  [ "$i" = 40 ] && { echo "API never became healthy — check: sudo docker compose logs api"; exit 1; }
done

echo
echo "── Smoke checks"
curl -s "http://127.0.0.1/api/v1/health?deep=1"; echo
curl -s -o /dev/null -w "  /updates/latest.yml → %{http_code}\n" http://127.0.0.1/updates/latest.yml

echo
echo "══════════════════════════════════════════════════════════"
echo "Cutover complete. Register this server + samithi on the console with:"
echo "  server:   code=prod  api_url=http://141.147.75.132/api/v1"
echo "  samithi:  slug=$SLUG  db_name=$DB_NAME  db_user=$DB_USER"
echo "  db_password: $TEN_PW"
echo "  tenant JWT secret (for TENANT_JWT_SECRET_PROD on the platform): <legacy JWT_SECRET>"
echo "ROLLBACK: sudo docker compose down && sudo systemctl start nginx && pm2 restart esamithi-api"
echo "══════════════════════════════════════════════════════════"
