import { chromium } from '@playwright/test'
import { readFileSync } from 'node:fs'
const out = process.argv[2]
const base = process.argv[3] || 'https://console.esamithi.com/app/'
const pass = readFileSync('/private/tmp/claude-501/-Volumes-Data-eSamithi/5e21abd3-ba77-42bb-920e-2580d30509a3/scratchpad/qa-gate-pass.txt', 'utf8').trim()
const b = await chromium.launch({ channel: 'chrome' })
const ctx = await b.newContext({ httpCredentials: { username: 'esamithi', password: pass }, viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2, colorScheme: 'dark' })
const p = await ctx.newPage()
await p.addInitScript(() => { try { localStorage.setItem('esamithi-theme', 'dark') } catch {} })
await p.goto(base + 'login')
await p.getByLabel(/samithi code/i).fill('TES-5155')
await p.getByRole('button', { name: /find samithi/i }).click()
await p.getByLabel(/username/i).fill('admin')
await p.getByLabel(/^password/i).fill('admin123')
await p.getByRole('button', { name: /^sign in$/i }).click()
await p.waitForURL(/dashboard/, { timeout: 25000 })
await p.waitForTimeout(2500)
await p.screenshot({ path: `${out}/dashboard.png` })
await p.goto(base + 'members'); await p.waitForTimeout(2500)
await p.screenshot({ path: `${out}/members.png` })
await p.goto(base + 'loans'); await p.waitForTimeout(2500)
await p.screenshot({ path: `${out}/loans.png` })
await p.goto(base + 'incomes?create=1'); await p.waitForTimeout(2500)
await p.screenshot({ path: `${out}/form.png` })
console.log('shots written to', out)
await b.close()
